name: automatyczne budowanie - windows

on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches:
      - master
  workflow_dispatch:

defaults:
  runs:
    shell: powershell
    os: windows-latest

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Example Step
        run: echo "Hello, World!"
