name: automatyczne budowanie - windows

on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  first-job:
    runs-on: windows-latest
    steps:
        - run: node --version
